version: "3.3"
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
      - "8000:8000" # used for debug
    environment:
      # start tomcat catalina on debug mode 
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    volumes:
      - ./target/image-search-api:/usr/local/tomcat/webapps/ROOT
