version: "3.3"
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
      - "8000:8000" # used for debug
      - "9010:9010" # used for debug
    environment:
      # start tomcat catalina on debug mode 
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
    volumes:
      - ./target/image-search-api:/usr/local/tomcat/webapps/ROOT
